# Config reload
bind r source-file ~/.tmux.conf \; display "Tmux config updated"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# Custom added
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'
## set -g @plugin 'catppuccin/tmux'
set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g status-position top
set -sg escape-time 50
#
set -g @plugin 'jaclu/tmux-menus' # PREFIX + backslash
set -g @plugin 'laktak/extrakto' # PREFIX + TAB
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
## set -g @plugin 'Morantron/tmux-fingers'
## set -g @plugin 'olimorris/tmux-pomodoro-plus'
set -g @plugin 'sainnhe/tmux-fzf'

set -g @plugin 'fcsonline/tmux-thumbs' #CTRL + B + SPACE
#run-shell ~/.tmux/plugins/tmux-thumbs/tmux-thumbs.tmux

## set -g status-right "#{pomodoro_status}"

# TOKYO NIGHT
set -g @theme_variation "storm"

setw -g mode-keys vi
set-window-option -g mode-keys vi
set -g mouse on
set -g renumber-windows on

# Key bindings for adjusting panes size
bind-key K resize-pane -U # up
bind-key J resize-pane -D # down
bind-key L resize-pane -R # right
bind-key H resize-pane -L # left
bind-key m resize-pane -Z # maximize

# Switching Panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind C-l send-keys 'C-l'

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
# bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# Fixed issue with colors
#set-option -sa terminal-overrides ",xterm-256color:Tc"

# Set base index to 1
set -g base-index 1
setw -g pane-base-index 1

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
